import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd

data = pd.read_csv("project_file.csv")
lstyear = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012]
lstmurder = []
lstrape = []
lstrobbery = []
lsttheft = []
lstriots = []
lstcheating = []
lstdowry = []

##Year Wise Data Calculate For Murder
m01=data['murder'][data['year'] == 2001].sum()
lstmurder.append(m01)
m02=data['murder'][data['year'] == 2002].sum()
lstmurder.append(m02)
m03=data['murder'][data['year'] == 2003].sum()
lstmurder.append(m03)
m04=data['murder'][data['year'] == 2004].sum()
lstmurder.append(m04)
m05=data['murder'][data['year'] == 2005].sum()
lstmurder.append(m05)
m06=data['murder'][data['year'] == 2006].sum()
lstmurder.append(m06)
m07=data['murder'][data['year'] == 2007].sum()
lstmurder.append(m07)
m08=data['murder'][data['year'] == 2008].sum()
lstmurder.append(m08)
m09=data['murder'][data['year'] == 2009].sum()
lstmurder.append(m09)
m10=data['murder'][data['year'] == 2010].sum()
lstmurder.append(m10)
m11=data['murder'][data['year'] == 2011].sum()
lstmurder.append(m11)
m12=data['murder'][data['year'] == 2012].sum()
lstmurder.append(m12)

murdersummary = []
murdersummary=data['murder'].describe()
print("\nMurder Crime Summary ")
print(murdersummary)

##Year Wise Data Calculate For Rape
r01=data['rape'][data['year'] == 2001].sum()
lstrape.append(r01)
r02=data['rape'][data['year'] == 2002].sum()
lstrape.append(r02)
r03=data['rape'][data['year'] == 2003].sum()
lstrape.append(r03)
r04=data['rape'][data['year'] == 2004].sum()
lstrape.append(r04)
r05=data['rape'][data['year'] == 2005].sum()
lstrape.append(r05)
r06=data['rape'][data['year'] == 2006].sum()
lstrape.append(r06)
r07=data['rape'][data['year'] == 2007].sum()
lstrape.append(r07)
r08=data['rape'][data['year'] == 2008].sum()
lstrape.append(r08)
r09=data['rape'][data['year'] == 2009].sum()
lstrape.append(r09)
r10=data['rape'][data['year'] == 2010].sum()
lstrape.append(r10)
r11=data['rape'][data['year'] == 2011].sum()
lstrape.append(r11)
r12=data['rape'][data['year'] == 2012].sum()
lstrape.append(r12)

rapesummary = []
rapesummary=data['rape'].describe()
print("\nRape Crime Summary ")
print(rapesummary)

##Year Wise Data Calculate For Robbery
rb01=data['robbery'][data['year'] == 2001].sum()
lstrobbery.append(rb01)
rb02=data['robbery'][data['year'] == 2002].sum()
lstrobbery.append(rb02)
rb03=data['robbery'][data['year'] == 2003].sum()
lstrobbery.append(rb03)
rb04=data['robbery'][data['year'] == 2004].sum()
lstrobbery.append(rb04)
rb05=data['robbery'][data['year'] == 2005].sum()
lstrobbery.append(rb05)
rb06=data['robbery'][data['year'] == 2006].sum()
lstrobbery.append(rb06)
rb07=data['robbery'][data['year'] == 2007].sum()
lstrobbery.append(rb07)
rb08=data['robbery'][data['year'] == 2008].sum()
lstrobbery.append(rb08)
rb09=data['robbery'][data['year'] == 2009].sum()
lstrobbery.append(rb09)
rb10=data['robbery'][data['year'] == 2010].sum()
lstrobbery.append(rb10)
rb11=data['robbery'][data['year'] == 2011].sum()
lstrobbery.append(rb11)
rb12=data['robbery'][data['year'] == 2012].sum()
lstrobbery.append(rb12)

robberysummary = []
robberysummary=data['robbery'].describe()
print("\nRobbery Crime Summary ")
print(robberysummary)

##Year Wise Data Calculate For theft
t01=data['theft'][data['year'] == 2001].sum()
lsttheft.append(t01)
t02=data['theft'][data['year'] == 2002].sum()
lsttheft.append(t02)
t03=data['theft'][data['year'] == 2003].sum()
lsttheft.append(t03)
t04=data['theft'][data['year'] == 2004].sum()
lsttheft.append(t04)
t05=data['theft'][data['year'] == 2005].sum()
lsttheft.append(t05)
t06=data['theft'][data['year'] == 2006].sum()
lsttheft.append(t06)
t07=data['theft'][data['year'] == 2007].sum()
lsttheft.append(t07)
t08=data['theft'][data['year'] == 2008].sum()
lsttheft.append(t08)
t09=data['theft'][data['year'] == 2009].sum()
lsttheft.append(t09)
t10=data['theft'][data['year'] == 2010].sum()
lsttheft.append(t10)
t11=data['theft'][data['year'] == 2011].sum()
lsttheft.append(t11)
t12=data['theft'][data['year'] == 2012].sum()
lsttheft.append(t12)

theftsummary = []
theftsummary=data['theft'].describe()
print("\nTheft Crime Summary ")
print(theftsummary)

##Year Wise Data Calculate For riots
r01=data['riots'][data['year'] == 2001].sum()
lstriots.append(r01)
r02=data['riots'][data['year'] == 2002].sum()
lstriots.append(r02)
r03=data['riots'][data['year'] == 2003].sum()
lstriots.append(r03)
r04=data['riots'][data['year'] == 2004].sum()
lstriots.append(r04)
r05=data['riots'][data['year'] == 2005].sum()
lstriots.append(r05)
r06=data['riots'][data['year'] == 2006].sum()
lstriots.append(r06)
r07=data['riots'][data['year'] == 2007].sum()
lstriots.append(r07)
r08=data['riots'][data['year'] == 2008].sum()
lstriots.append(r08)
r09=data['riots'][data['year'] == 2009].sum()
lstriots.append(r09)
r10=data['riots'][data['year'] == 2010].sum()
lstriots.append(r10)
r11=data['riots'][data['year'] == 2011].sum()
lstriots.append(r11)
r12=data['riots'][data['year'] == 2012].sum()
lstriots.append(r12)

riotssummary = []
riotssummary=data['riots'].describe()
print("\nRiots Crime Summary ")
print(riotssummary)

##Year Wise Data Calculate For cheating
c01=data['cheating'][data['year'] == 2001].sum()
lstcheating.append(c01)
c02=data['cheating'][data['year'] == 2002].sum()
lstcheating.append(c02)
c03=data['cheating'][data['year'] == 2003].sum()
lstcheating.append(c03)
c04=data['cheating'][data['year'] == 2004].sum()
lstcheating.append(c04)
c05=data['cheating'][data['year'] == 2005].sum()
lstcheating.append(c05)
c06=data['cheating'][data['year'] == 2006].sum()
lstcheating.append(c06)
c07=data['cheating'][data['year'] == 2007].sum()
lstcheating.append(c07)
c08=data['cheating'][data['year'] == 2008].sum()
lstcheating.append(c08)
c09=data['cheating'][data['year'] == 2009].sum()
lstcheating.append(c09)
c10=data['cheating'][data['year'] == 2010].sum()
lstcheating.append(c10)
c11=data['cheating'][data['year'] == 2011].sum()
lstcheating.append(c11)
c12=data['cheating'][data['year'] == 2012].sum()
lstcheating.append(c12)

cheatingsummary = []
cheatingsummary=data['cheating'].describe()
print("\nCheating Crime Summary ")
print(cheatingsummary)

##Year Wise Data Calculate For dowry_deaths
d01=data['dowry_deaths'][data['year'] == 2001].sum()
lstdowry.append(d01)
d02=data['dowry_deaths'][data['year'] == 2002].sum()
lstdowry.append(d02)
d03=data['dowry_deaths'][data['year'] == 2003].sum()
lstdowry.append(d03)
d04=data['dowry_deaths'][data['year'] == 2004].sum()
lstdowry.append(d04)
d05=data['dowry_deaths'][data['year'] == 2005].sum()
lstdowry.append(d05)
d06=data['dowry_deaths'][data['year'] == 2006].sum()
lstdowry.append(d06)
d07=data['dowry_deaths'][data['year'] == 2007].sum()
lstdowry.append(d07)
d08=data['dowry_deaths'][data['year'] == 2008].sum()
lstdowry.append(d08)
d09=data['dowry_deaths'][data['year'] == 2009].sum()
lstdowry.append(d09)
d10=data['dowry_deaths'][data['year'] == 2010].sum()
lstdowry.append(d10)
d11=data['dowry_deaths'][data['year'] == 2011].sum()
lstdowry.append(d11)
d12=data['dowry_deaths'][data['year'] == 2012].sum()
lstdowry.append(d12)

ddsummary = []
ddsummary=data['dowry_deaths'].describe()
print("\nDowry_Deaths Crime Summary ")
print(ddsummary)

plt.plot(lstyear, lstdowry, color='yellow')



plt.plot(lstyear, lstcheating, color='black')
plt.plot(lstyear, lstriots, color='red')
plt.plot(lstyear, lstmurder, color='g')
plt.plot(lstyear, lstrape, color='orange')
plt.plot(lstyear, lstrobbery, color='blue')
plt.plot(lstyear, lsttheft, color='yellow')


plt.ylabel('Total Numbers of different Crimes')
plt.xlabel('Years')
plt.title('Total Crimes in India From 2001 To 2012')
g_patch = mpatches.Patch(color='g', label='Murder')
orange_patch = mpatches.Patch(color='orange', label='Rape')
blue_patch = mpatches.Patch(color='blue', label='Robbery')
yellow_patch = mpatches.Patch(color='yellow', label='Theft')
red_patch = mpatches.Patch(color='red', label='riots')
black_patch = mpatches.Patch(color='black', label='Cheating')
purple_patch = mpatches.Patch(color='purple', label='dowry')
plt.legend(handles=[g_patch,orange_patch,blue_patch,yellow_patch,red_patch,black_patch,purple_patch])
plt.show()
plt.savefig("Crime_India")
